<Project>

  <PropertyGroup>
    <HonuaSdkVersionPrefix>0.1.0</HonuaSdkVersionPrefix>
    <HonuaSdkVersionSuffix>alpha.1</HonuaSdkVersionSuffix>
    <VersionPrefix>$(HonuaSdkVersionPrefix)</VersionPrefix>
    <VersionSuffix>$(HonuaSdkVersionSuffix)</VersionSuffix>
    <Version Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <Version Condition="'$(VersionSuffix)' == ''">$(VersionPrefix)</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <AssemblyVersion>$(VersionPrefix).0</AssemblyVersion>
    <FileVersion>$(VersionPrefix).0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

</Project>
