CREATE TABLE IF NOT EXISTS public.sdk_demo_points
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text NOT NULL,
    status text NOT NULL,
    geom geometry(Point, 4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_sdk_demo_points_geom
    ON public.sdk_demo_points
    USING GIST (geom);

TRUNCATE TABLE public.sdk_demo_points RESTART IDENTITY;

INSERT INTO public.sdk_demo_points (name, category, status, geom)
VALUES
    ('Honolulu Harbor', 'port', 'active', ST_SetSRID(ST_MakePoint(-157.866222, 21.306944), 4326)),
    ('Kakaako Waterfront', 'park', 'active', ST_SetSRID(ST_MakePoint(-157.858200, 21.289600), 4326)),
    ('Diamond Head Lookout', 'landmark', 'active', ST_SetSRID(ST_MakePoint(-157.804300, 21.261900), 4326));
