// Copyright (c) Honua. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root.

using System.Text.Json;
using System.Text.Json.Serialization;
using Honua.Sdk.Abstractions.Serialization;

namespace Honua.Sdk.Abstractions;

/// <summary>
/// Normalized RFC 7807 (<c>application/problem+json</c>) problem document, used as the single
/// problem-details model across every <c>Honua.Sdk.*</c> REST client and surfaced uniformly via
/// <see cref="HonuaException.ProblemDetails"/>.
/// </summary>
public sealed record HonuaProblemDetails
{
    /// <summary>A URI reference identifying the problem type.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>A short, human-readable summary of the problem type.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>The HTTP status code generated by the origin server, if echoed in the body.</summary>
    [JsonPropertyName("status")]
    public int? Status { get; init; }

    /// <summary>A human-readable explanation specific to this occurrence of the problem.</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; init; }

    /// <summary>A URI reference identifying the specific occurrence of the problem.</summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; init; }
}

/// <summary>
/// Shared parser for RFC 7807 problem-details bodies. Replaces the per-client reimplementations so
/// every REST client extracts <c>type</c>/<c>title</c>/<c>detail</c>/<c>status</c>/<c>instance</c>
/// identically and via source-generated JSON.
/// </summary>
public static class HonuaProblemDetailsParser
{
    /// <summary>
    /// Attempts to parse <paramref name="body"/> as an RFC 7807 problem-details document.
    /// </summary>
    /// <param name="body">The raw response body.</param>
    /// <param name="problem">The parsed problem, or <see langword="null"/> when the body is empty or not problem JSON.</param>
    /// <returns><see langword="true"/> when a problem document was parsed.</returns>
    public static bool TryParse(string? body, out HonuaProblemDetails? problem)
    {
        problem = null;
        if (string.IsNullOrWhiteSpace(body))
        {
            return false;
        }

        try
        {
            problem = JsonSerializer.Deserialize(body, HonuaAbstractionsJsonContext.Default.HonuaProblemDetails);
            // A successful deserialize is not enough: unknown members are ignored, so an
            // unrelated object such as an Admin {success,message} envelope would otherwise be
            // reported as an empty RFC 7807 document.
            if (problem is null || problem.Type is null && problem.Title is null && problem.Status is null
                && problem.Detail is null && problem.Instance is null)
            {
                problem = null;
                return false;
            }

            return true;
        }
        catch (JsonException)
        {
            // Body is not a parseable problem+json document; callers fall back to the raw body.
            problem = null;
            return false;
        }
    }

    /// <summary>
    /// Parses <paramref name="body"/> and selects the best human-readable message, falling back to
    /// <paramref name="fallback"/> when no problem detail/title is present.
    /// </summary>
    /// <param name="body">The raw response body.</param>
    /// <param name="fallback">The default message when the body carries no problem text.</param>
    /// <param name="problem">The parsed problem, if any.</param>
    /// <returns>The resolved error message.</returns>
    public static string ResolveMessage(string? body, string fallback, out HonuaProblemDetails? problem)
    {
        _ = TryParse(body, out problem);
        return problem?.Detail ?? problem?.Title ?? fallback;
    }
}
