// Copyright (c) Honua. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root.

using System.Text.Json;
using System.Text.Json.Serialization;
using Honua.Sdk.Abstractions.Features;
using Honua.Sdk.Admin.Catalog;
using Honua.Sdk.Admin.Models;

namespace Honua.Sdk.Admin;

/// <summary>
/// Source-generated JSON serializer context for AOT-compatible serialization.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ApiResponse<ServiceSummary[]>))]
[JsonSerializable(typeof(CatalogFeatureServerServiceInfo))]
[JsonSerializable(typeof(CatalogFeatureServerLayerInfo))]
[JsonSerializable(typeof(SourceDescriptor))]
[JsonSerializable(typeof(ApiResponse<ServiceSettingsResponse>))]
[JsonSerializable(typeof(ApiResponse<LayerMetadataResponse>))]
[JsonSerializable(typeof(ApiResponse<SecureConnectionSummary[]>))]
[JsonSerializable(typeof(ApiResponse<SecureConnectionDetail>))]
[JsonSerializable(typeof(ApiResponse<SecureConnectionSummary>))]
[JsonSerializable(typeof(ApiResponse<ConnectionTestResult>))]
[JsonSerializable(typeof(ApiResponse<EncryptionValidationResult>))]
[JsonSerializable(typeof(ApiResponse<KeyRotationResult>))]
[JsonSerializable(typeof(ApiResponse<MetadataResource[]>))]
[JsonSerializable(typeof(ApiResponse<MetadataResource>))]
[JsonSerializable(typeof(MetadataResourceResponse))]
[JsonSerializable(typeof(ApiResponse<MetadataManifest>))]
[JsonSerializable(typeof(ApiResponse<ManifestApplyResult>))]
[JsonSerializable(typeof(ApiResponse<AdminVersionResponse>))]
[JsonSerializable(typeof(ApiResponse<AdminCapabilitiesResponse>))]
[JsonSerializable(typeof(ApiResponse<PublishedLayerSummary[]>))]
[JsonSerializable(typeof(ApiResponse<PublishedLayerSummary>))]
[JsonSerializable(typeof(ApiResponse<LayerStyleResponse>))]
[JsonSerializable(typeof(ApiResponse<RecentError[]>))]
[JsonSerializable(typeof(ApiResponse<TelemetryStatus>))]
[JsonSerializable(typeof(ApiResponse<MigrationStatus>))]
[JsonSerializable(typeof(ApiResponse<DeployPreflightResult>))]
[JsonSerializable(typeof(ApiResponse<DeployPlan>))]
[JsonSerializable(typeof(ApiResponse<DeployOperation>))]
[JsonSerializable(typeof(ApiResponse<OidcProviderResponse[]>))]
[JsonSerializable(typeof(ApiResponse<OidcProviderResponse>))]
[JsonSerializable(typeof(ApiResponse<OidcProviderTestResponse>))]
[JsonSerializable(typeof(ApiResponse<IdentityProvidersResponse>))]
[JsonSerializable(typeof(ApiResponse<IdentityProviderTestResult>))]
[JsonSerializable(typeof(ApiResponse<RoleResponse[]>))]
[JsonSerializable(typeof(ApiResponse<RoleResponse>))]
[JsonSerializable(typeof(ApiResponse<PermissionGrantResponse[]>))]
[JsonSerializable(typeof(ApiResponse<UserListResponse>))]
[JsonSerializable(typeof(ApiResponse<UserResponse>))]
[JsonSerializable(typeof(ApiResponse<EffectivePermissionsResponse>))]
[JsonSerializable(typeof(ApiResponse<LicenseStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<LicenseEntitlement[]>))]
[JsonSerializable(typeof(ApiResponse<AlertZoneResponse[]>))]
[JsonSerializable(typeof(ApiResponse<AlertZoneResponse>))]
[JsonSerializable(typeof(ApiResponse<AlertRuleResponse[]>))]
[JsonSerializable(typeof(ApiResponse<AlertRuleResponse>))]
[JsonSerializable(typeof(FeatureEventReplayResponse))]
[JsonSerializable(typeof(FeatureChangeEvent))]
[JsonSerializable(typeof(FeatureChangeEvent[]))]
[JsonSerializable(typeof(ApiResponse<SubscriberListResponse>))]
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(TableDiscoveryResponse))]
[JsonSerializable(typeof(MigrationInventoryScanRequest))]
[JsonSerializable(typeof(MigrationSourceInventoryArtifact))]
[JsonSerializable(typeof(MigrationSourceIdentity))]
[JsonSerializable(typeof(MigrationInventoryAuthPosture))]
[JsonSerializable(typeof(MigrationInventoryCompleteness))]
[JsonSerializable(typeof(MigrationInventorySummary))]
[JsonSerializable(typeof(MigrationCompatibilityAssessment))]
[JsonSerializable(typeof(MigrationInventoryContainer))]
[JsonSerializable(typeof(MigrationInventoryResource))]
[JsonSerializable(typeof(MigrationInventoryField))]
[JsonSerializable(typeof(MigrationInventoryCodedValue))]
[JsonSerializable(typeof(MigrationInventoryStyle))]
[JsonSerializable(typeof(MigrationExternalDependency))]
[JsonSerializable(typeof(MigrationSpatialReferenceInfo))]
[JsonSerializable(typeof(MigrationManifestArtifact))]
[JsonSerializable(typeof(MigrationManifestSummary))]
[JsonSerializable(typeof(MigrationManifestTargetResource))]
[JsonSerializable(typeof(MigrationManifestStyleAction))]
[JsonSerializable(typeof(MigrationManifestReviewItem))]
[JsonSerializable(typeof(MigrationManifestTranslationOptions))]
[JsonSerializable(typeof(MigrationParityEvidenceArtifact))]
[JsonSerializable(typeof(MigrationParityEvidenceSection))]
[JsonSerializable(typeof(MigrationParityEvidenceItem))]
[JsonSerializable(typeof(MigrationCutoverReadinessSummary))]
[JsonSerializable(typeof(MigrationCutoverReadinessItem))]
[JsonSerializable(typeof(MigrationReadinessAttestation))]
[JsonSerializable(typeof(MigrationReadinessAttestationItem))]
[JsonSerializable(typeof(RecentErrorsResponse))]
[JsonSerializable(typeof(TelemetryStatus))]
[JsonSerializable(typeof(MigrationStatus))]
[JsonSerializable(typeof(DeployPreflightResult))]
[JsonSerializable(typeof(DeployPlan))]
[JsonSerializable(typeof(DeployOperation))]
[JsonSerializable(typeof(UpdateProtocolsRequest))]
[JsonSerializable(typeof(UpdateMapServerSettingsRequest))]
[JsonSerializable(typeof(UpdateAccessPolicyRequest))]
[JsonSerializable(typeof(UpdateTimeInfoRequest))]
[JsonSerializable(typeof(UpdateLayerMetadataRequest))]
[JsonSerializable(typeof(CreateSecureConnectionRequest))]
[JsonSerializable(typeof(UpdateSecureConnectionRequest))]
[JsonSerializable(typeof(MetadataResource))]
[JsonSerializable(typeof(ManifestApplyRequest))]
[JsonSerializable(typeof(PublishLayerRequest))]
[JsonSerializable(typeof(LayerEnabledRequest))]
[JsonSerializable(typeof(LayerStyleUpdateRequest))]
[JsonSerializable(typeof(CreateDeployPlanRequest))]
[JsonSerializable(typeof(CreateDeployOperationRequest))]
[JsonSerializable(typeof(SubmitDeployOperationRequest))]
[JsonSerializable(typeof(RollbackDeployOperationRequest))]
[JsonSerializable(typeof(CreateOidcProviderRequest))]
[JsonSerializable(typeof(UpdateOidcProviderRequest))]
[JsonSerializable(typeof(CreateRoleRequest))]
[JsonSerializable(typeof(UpdateRoleRequest))]
[JsonSerializable(typeof(SetPermissionsRequest))]
[JsonSerializable(typeof(PermissionGrantRequest))]
[JsonSerializable(typeof(UpdateUserRolesRequest))]
[JsonSerializable(typeof(AlertZoneRequest))]
[JsonSerializable(typeof(AlertRuleRequest))]
[JsonSerializable(typeof(LicenseStatusResponse))]
[JsonSerializable(typeof(LicenseEntitlement))]
[JsonSerializable(typeof(LicenseEntitlement[]))]
[JsonSerializable(typeof(RasterImportResult))]
[JsonSerializable(typeof(RasterFormatsResponse))]
[JsonSerializable(typeof(JsonElement))]
internal sealed partial class HonuaAdminJsonContext : JsonSerializerContext
{
}
