name: Docs

on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build DocFX site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Cache NuGet packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/.nuget/packages
          key: ${{ github.repository }}-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ github.repository }}-${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1
        with:
          global-json-file: global.json

      - name: Configure GitHub Packages
        run: dotnet nuget update source github-honua --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Restore
        run: dotnet restore Honua.Sdk.sln --locked-mode

      - name: Build solution
        run: dotnet build Honua.Sdk.sln --configuration Release /p:TreatWarningsAsErrors=true

      - name: Install DocFX
        run: dotnet tool update --global docfx

      - name: Build DocFX site
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          docfx docs/docfx.json

      - name: Configure GitHub Pages
        if: vars.DEPLOY_GITHUB_PAGES == 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload DocFX site artifact
        if: vars.DEPLOY_GITHUB_PAGES == 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: docs/_site

      - name: Deploy to GitHub Pages
        id: deployment
        if: vars.DEPLOY_GITHUB_PAGES == 'true' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
